let libro = [
    {
        titulo: "Culpa Mia",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 56.000 col.",
        formato: "Tapa blanda",
        isbn: "9788490438664",
        descripcion: "Nicholas Leister ha sido creado para amargarme la vida. Alto, ojos azules, pelo negro como la noche... Suena genial ¿verdad? Pues no tanto cuando te enteras de que va a ser tu hermanastro y además representa todo de lo que has estado huyendo desde que tienes uso de razón.Peligro fue lo primero que me vino a la cabeza cuando lo conocí y descubrí que mantiene una doble vida oculta de su padre multimillonario. ¿Cómo termine cayendo en sus redes? Fácil: con esos ojos es capaz de poner tu mundo patas arriba.",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "08/06/2017",
        editorial: "MONTENA",
        paginas: "448",
        dimensiones: {
            alto: "21.5 cm",
            ancho: "15.2 cm",
            grueso: "3.2 cm",
        },
        peso: "544 gr",
    },

    {
        titulo: "Culpa tuya",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 65.000 col.",
        formato: "Tapa blanda bolsillo",
        isbn: "9788413142029",
        descripcion: "Cuando Noah se enamoró de Nick sabía que su relación no iba a ser fácil: son polos opuestos, fuego y electricidad, y cuando están juntos saltan chispas... en todos los sentidos. Hasta ahora, la pasión ha sido más fuerte que el orgullo, pero la diferencia de edad, la universidad, las fiestas, sus padres y los fantasmas que acechan a los dos les ponen a prueba una y otra vez, como una bomba de relojería que amenaza con hacerles estallar. ¿Está Noah realmente preparada para enfrentarse a sus miedos y volver a confiar en alguien? ¿Podrá Nicholas dejar atrás su pasado y abrir el corazón a una sola persona?",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "21/09/2017",
        editorial: "B de Bolsillo",
        paginas: "448",
        dimensiones: {
            alto: "19.1 cm",
            ancho: "13 cm",
            grueso: "2.8 cm",
        },
        peso: "325 gr",
    },

    {
        titulo: "Culpa nuestra",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 65.000 col.",
        formato: "Tapa blanda",
        isbn: "9788490438893",
        descripcion: "La relación de Nick y Noah está pasando por su peor momento, y parece que nada podrá volver a ser como antes... Van a tener que pasar por muchas cosas para finalmente comprender si de verdad están hechos el uno para el otro o si por lo contrario, estar separados es lo que de verdad les conviene. Pero ¿acaso se puede olvidar un amor tan fuerte? ¿Cómo pueden borrarse los recuerdos tatuados en el corazón? El amor no siempre es suficiente y el perdón a veces no basta para solucionar las cosas. ¿Serán capaces de dejar atrás el pasado y volver a empezar?",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "01/02/2018",
        editorial: "Montena",
        paginas: "448",
        dimensiones: {
            alto: "21.5 cm",
            ancho: "15.4 cm",
            grueso: "3.2 cm",
        },
        peso: "540 gr",
    },

    {
        titulo: "A traves de mi ventana",
        autor: "Ariana Godoy",
        genero: "Romance adolescente",
        idioma: "Catellano",
        precio: "$ 62.000 col.",
        formato: "Tapa blanda",
        isbn: "9788420451916",
        descripcion: "Raquel lleva toda la vida loca por Ares, su atractivo y misterioso  vecino. Lo observa sin ser vista desde su ventana y es que, muy a su pesar, no han intercambiado ni una triste palabra. Lo que Raquel no sabe es que eso está a punto de cambiar...",
        ubicacion: "Panamericana",
        fecha_publicacion: "16/05/2019",
        editorial: "Alfaguara",
        paginas: "416",
        dimensiones: {
            alto: "21.6 cm",
            ancho: "15.2 cm",
            grueso: "2.7 cm",
        },
        peso: "515 gr",
    },

    {
        titulo: "A traves de ti",
        autor: "Ariana Godoy",
        genero: "Romance adolescente",
        idioma: "Castellano",
        precio: "$ 62.000 col.",
        formato: "Tapa blanda",
        isbn: "9788418483509",
        descripcion: "Nada es tan fácil y simple en la vida de alguien como yo. ¿Que se siente al vivir con tres chicos tan guapos? Eres tan afortunada. Que envidia. Vivir con esas bellezas, que privilegio. ¿Cómo puedes vivir con ellos? ¿Te has tirado alguno? ¿Podrías conseguirme su número de telefono? Eso es solo un poco de lo que he tenido que lidiar desde que los chicos  Hidalgo crecieron y se convirtieron en el sueño húmedo de todas las  chicas de este lugar. Artemis, Ares y Apolo Hidalgo son los responsables  de muchos suspiros de chicas en las calles y con los que crecí aunque no  seamos familia. Muchas personas me creen afortunada, pero están tan  equivocados sobre mi vida, no saben mi historia, no todo es color de rosa en la vida de una chica como yo.",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "23/09/2021",
        editorial: "Montena",
        paginas: "336",
        dimensiones: {
            alto: "21.5 cm",
            ancho: "15.3 cm",
            grueso: "2.3 cm",
        },
        peso: "424 gr",
    },

    {
        titulo: "A traves de la lluvia",
        autor: "Ariana Godoy",
        genero: "Romance adolescente",
        idioma: "Castellano",
        precio: "$ 59.000 col.",
        formato: "Tapa blanda",
        isbn: "9788418483196",
        descripcion: "Apolo Hidalgo está emocionado por enfrentarse a una nueva etapa de su  vida: la  universidad. Su sueño es estudiar psicología y ayudar a los  demás. Sin embargo, esa ilusión se rompe cuando es atacado y golpeado en  un callejón durante una noche lluviosa e, irónicamente, así es como la conoce a ella. A Rain. La chica del paraguas lo salva, y se le queda grabada en la memoria.  Cuando finalmente se vuelven a encontrar, Apolo queda todavía más  prendado de Rain y, a traves de ella, conoce a Xan, el dueño de un cafe donde pasan el rato. A medida que los tres se conocen, Apolo se dará cuenta que Rain y Xan ocultan mucho más de lo que uno se puede imaginar. Apolo es un chico lleno de buenas intenciones, pero eso, en la vida, no es garantía de nada... especialmente en el amor. Ver menos",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "27/10/2022",
        editorial: "Montena",
        paginas: "288",
        dimensiones: {
            alto: "21.6 cm",
            ancho: "15.2 cm",
            grueso: "2 cm",
        },
        peso: "356 gr",
    },

    {
        titulo: "Still with you",
        autor: "Lily del Pilar",
        genero: "Ficcion",
        idioma: "Castellano",
        precio: "$ 62.000 col.",
        formato: "Tapa blanda",
        isbn: "9788408254546",
        descripcion: "El oficial Jong Sungguk pensó que esa tarde de lluvia sería como cualquier otra: más inspecciones de rutina en un vecindario de clase media de la ciudad de Daegu, Corea del Sur. Lo que nunca imaginó es que dentro de una casa aparentemente normal encontraría a una mujer muerta y a un chico, de nombre Moon Daehyun, encerrado en el ático. Y lo que menos podía esperar es que ese chico cambiaría su vida para siempre.",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "02/03/2022",
        editorial: "Crossbooks",
        paginas: "368",
        dimensiones: {
            alto: "22.5 cm",
            ancho: "14.5 cm",
            grueso: "2.1 cm",
        },
        peso: "562 gr",
    },



    
]