let libro = [
    {
        titulo: "Culpa Mia",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 56.000 col.",
        formato: "Tapa blanda",
        isbn: "9788490438664",
        descripcion: "Nicholas Leister ha sido creado para amargarme la vida. Alto, ojos azules, pelo negro como la noche... Suena genial ¿verdad? Pues no tanto cuando te enteras de que va a ser tu hermanastro y además representa todo de lo que has estado huyendo desde que tienes uso de razón.Peligro fue lo primero que me vino a la cabeza cuando lo conocí y descubrí que mantiene una doble vida oculta de su padre multimillonario. ¿Cómo termine cayendo en sus redes? Fácil: con esos ojos es capaz de poner tu mundo patas arriba.",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "08/06/2017",
        editorial: "MONTENA",
        paginas: "448",
        dimensiones: {
            alto: "21.5 cm",
            ancho: "15.2 cm",
            grueso: "3.2 cm",
        },
        peso: "544 gr",
    },

    {
        titulo: "Culpa tuya",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 65.000 col.",
        formato: "Tapa blanda bolsillo",
        isbn: "9788413142029",
        descripcion: "Cuando Noah se enamoró de Nick sabía que su relación no iba a ser fácil: son polos opuestos, fuego y electricidad, y cuando están juntos saltan chispas... en todos los sentidos. Hasta ahora, la pasión ha sido más fuerte que el orgullo, pero la diferencia de edad, la universidad, las fiestas, sus padres y los fantasmas que acechan a los dos les ponen a prueba una y otra vez, como una bomba de relojería que amenaza con hacerles estallar. ¿Está Noah realmente preparada para enfrentarse a sus miedos y volver a confiar en alguien? ¿Podrá Nicholas dejar atrás su pasado y abrir el corazón a una sola persona?",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "21/09/2017",
        editorial: "B de Bolsillo",
        paginas: "448",
        dimensiones: {
            alto: "19.1 cm",
            ancho: "13 cm",
            grueso: "2.8 cm",
        },
        peso: "325 gr",
    },

    {
        titulo: "Culpa nuestra",
        autor: "Mercedes Ron",
        genero: "Romance adolescente",
        idioma: "Español España",
        precio: "$ 65.000 col.",
        formato: "Tapa blanda",
        isbn: "9788490438893",
        descripcion: "La relación de Nick y Noah está pasando por su peor momento, y parece que nada podrá volver a ser como antes... Van a tener que pasar por muchas cosas para finalmente comprender si de verdad están hechos el uno para el otro o si por lo contrario, estar separados es lo que de verdad les conviene. Pero ¿acaso se puede olvidar un amor tan fuerte? ¿Cómo pueden borrarse los recuerdos tatuados en el corazón? El amor no siempre es suficiente y el perdón a veces no basta para solucionar las cosas. ¿Serán capaces de dejar atrás el pasado y volver a empezar?",
        estado: "Nuevo",
        ubicacion: "Panamericana",
        fecha_publicacion: "01/02/2018",
        editorial: "Montena",
        paginas: "448",
        dimensiones: {
            alto: "21.5 cm",
            ancho: "15.4 cm",
            grueso: "3.2 cm",
        },
        peso: "540 gr",
    },

    {
        titulo: "A traves de mi ventana",
        autor: "Ariana Godoy",
        genero: "Romance adolescente",
        idioma: "Catellano",
        precio: "$ 62.000 col.",
        formato: "Tapa blanda",
        isbn: "9788420451916",
        descripcion: "Raquel lleva toda la vida loca por Ares, su atractivo y misterioso  vecino. Lo observa sin ser vista desde su ventana y es que, muy a su pesar, no han intercambiado ni una triste palabra. Lo que Raquel no sabe es que eso está a punto de cambiar...",
        ubicacion: "Panamericana",
        fecha_publicacion: "16/05/2019",
        editorial: "Alfaguara",
        paginas: "416",
        dimensiones: {
            alto: "21.6 cm",
            ancho: "15.2 cm",
            grueso: "2.7 cm",
        },
        peso: "515 gr",
    },


    
]